env:
  global:
    - CONAN_USERNAME: "tomghuang"
    - CONAN_LOGIN_USERNAME: "tomghuang"
    - CONAN_CHANNEL: "testing"
    - CONAN_UPLOAD: "UPLOAD_URL"

linux: &linux
  os: linux
  dist: xenial
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

osx: &osx
  os: osx
  language: generic

matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

install:
  - chmod +x tools/build
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
